# air configuration (https://github.com/cosmtrek/air)
root = "."
tmp_dir = "tmp"

[build]
  cmd = "make build"
  bin = "./.bin/api"
  include_ext = ["go","tpl","tmpl","html"]
  exclude_dir = ["assets","tmp","vendor"]

[color]
  main = "yellow"
  watcher = "cyan"
  build = "green"
  runner = "magenta"
