services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GO_VERSION: ${GO_VERSION:-latest}
      target: dev
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    environment:
      TSUDZURI_DATABASE_DSN: user=postgres password=postgres dbname=tsudzuri host=db port=5432 sslmode=disable
      ENABLE_STDOUT_TRACE_EXPORTER: true
    depends_on:
      - db
    command: make dev

  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8081:8080"
    environment:
      - SWAGGER_JSON=/openapi/tsudzuri.swagger.json
    volumes:
      - ./api/protobuf/gen/openapi/tsudzuri/v1:/openapi:ro
    depends_on:
      - api

  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tsudzuri
    ports:
      - "5432:5432"
    volumes:
      - ./resources/postgres/init:/docker-entrypoint-initdb.d

  testdb:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tsudzuri_test
    ports:
      - "5433:5432"
    volumes:
      - ./resources/postgres/init:/docker-entrypoint-initdb.d
