name: CD trigger

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  prod-release:
    uses: ./.github/workflows/ci.yaml
    with:
      environment: prod
      env_var_file: ./.github/env/prod.yaml
      enable_traffic_update: false
    secrets: inherit
